### ISSUE TITLE
add support for ffprobe

### ISSUE THREAD

**Issue by prabirshrestha** [nathanbabcock/ffmpeg-sidecar#17]
Seems like this downloads `ffmpeg` and `ffprobe` and correctly places both the files after extraction. But there are no equivalent functions for `ffprobe`. Would it be possible to add these?

* `ffprobe_version()`
* `ffprobe_path()`
* `FfprobeCommand`

**Comment by nathanbabcock** [comment]
Fine idea! I linked a PR which adds all of these except the `FfprobeCommand` wrapper. I'm totally open to it but it's out of scope for me right at the moment. If you have any ideas what the API for `FfprobeCommand` should look like (e.g. which aliases are most convenient and most-often used), please feel free to create a follow-up PR taking this as the starting point.

**Comment by prabirshrestha** [comment]
`ffprobe_path` is the most important one I need.

I use `ffprobe -print_format json -show_format -show_streams -loglevel quiet`.

It returns json which I then parse by serde_json so `FfprobeCommand` is not necessary for me.

**Comment by revofusion** [comment]
Just adding here, most common used command here is

  const args = [
    '-loglevel', 'fatal',
    '-print_format',  'json',
    '-show_format',
    '-hide_banner',
    '-i', path
  ]
