### ISSUE TITLE
ffprobe_path returns ffmpeg path

### ISSUE THREAD

**Issue by prabirshrestha** [nathanbabcock/ffmpeg-sidecar#20]
`ffprobe_path()` uses `sidecar_path()` which hardcodes `.join('ffmepg')`.

Seems like it needs `ffmpeg_sidecar_path()` and `ffprobe_sidecar_path()`.

**Comment by nathanbabcock** [comment]
@prabirshrestha thanks for pointing this out.

I'll merge a PR with the quick fix -- however I'll address this more thoroughly when also investigating using `ffmpeg-static` as the source of binaries. That will address a few other outstanding issues:

- Download path differs between `cargo test`, `cargo run`, and `cargo run --example` -- and sometimes the downloaded binary can't be found
- Some distributions do not include `ffprobe` in the first place
