### ISSUE TITLE
How to bundle as binary instead of running on runtime?

### ISSUE THREAD

**Issue by bliongosari1** [nathanbabcock/ffmpeg-sidecar#41]
Is there a way to install this library as a binary instead of downloading on runtime? 

Only functions I can see is 
`ffmpeg_sidecar::download::auto_download().unwrap();`

So users download it as part of the bundle instead of download the application, then calling this which downloads the ffmpeg again?

Not really a bug, appreciate the help

**Comment by nathanbabcock** [comment]
Rather than being bundled into a single binary, in that case you would want to include both `myprogram.exe` and `ffmpeg.exe` together side-by-side when you package or distribute your app, with ffmpeg being the so-called "sidecar" binary.

Then you can use the `FfmpegCommand::new_with_path(path_to_ffmpeg)` method to point to your bundled ffmpeg binary, but if they are in the same folder it should work automatically!

**Comment by bliongosari1** [comment]
Hi @nathanbabcock 

               
        let download_url = ffmpeg_download_url().unwrap_or("");
        let destination = ffmpeg_path_dir();
        let archive_path = download_ffmpeg_package(download_url, &destination);
        println!("archive_path: {:?}", archive_path);

        match archive_path {
            Ok(archive_path) => {
                println!("unpacking ffmpeg");
                let _ffmpeg = unpack_ffmpeg(&archive_path, &destination);
                println!("ffmpeg unpacked");
                let _version = ffmpeg_version_with_path(destination.join("ffmpeg"));
            }
            Err(_) => {
                println!("Error while downloading ffmpeg");
            }
        }
        
        
       
        
  When I try to install ffmpeg using the functions here it fails when unpacking with this error message 
  
  tar: Error opening archive: Failed to open '/Users/username/Library/Application Support/app_data/ffmpeg/ffmpeg7arm.zip'
  
  
  and when I check if its installed it will be false
  
      Command::new(ffmpeg_path_dir())
      .arg("-version")
      .create_no_window()
      .stderr(Stdio::null())
      .stdout(Stdio::null())
      .status()
      .map(|s| s.success())
      .unwrap_or_else(|_| false)
      
  Any thoughts?
