### ISSUE TITLE
There should be a method named `version()` to get the current version of installed ffmpeg 

### ISSUE THREAD

**Issue by VirtualPirate** [nathanbabcock/ffmpeg-sidecar#46]
There should be a method `command::check_current_version()` in the `command.rs` , that will return the version string, that can be matched against `download::check_latest_version()` . So, that the user can decide to download the updated versions, if exists..

If there is a existing way to solve this problem, then please give code examples

**Comment by nathanbabcock** [comment]
There is a function that does this called `ffmpeg_version`:

https://docs.rs/ffmpeg-sidecar/1.1.2/ffmpeg_sidecar/version/fn.ffmpeg_version.html

There's also a variant where you can pass a path to a specific binary.

**Comment by VirtualPirate** [comment]
Yaa, thanks.. My Bad. You can close the issue now
